### ISSUE TITLE
Speed...

### ISSUE THREAD

**Issue by rsilvers129** [Photonsters/Slicer#11]
I ran Photon Open Slicer and for a 1700 layer run it was 8:45 for time. ChiTuBox took 55 seconds, and Anycubic Photon Slicer took 35 seconds. How can they be doing it so much faster?

I can say that it is not running on my GPU for some reason. I have a 1080Ti and it is not being utilized.

**Comment by NardJ** [comment]
@rsilvers129 Did you manage to get it to run on GPU? (Use flags '-g True' and '-f False')
