### ISSUE TITLE
This happened!

### ISSUE THREAD

**Issue by X3msnake** [Photonsters/Slicer#5]
![image](https://user-images.githubusercontent.com/11083514/50490848-3a428e80-0a07-11e9-9acb-f14e14ecad0a.png)

**Comment by X3msnake** [comment]
I will dismiss this since I think it has to do with the dam meshmixer model
Even hollowing the model this is the result

![image](https://user-images.githubusercontent.com/11083514/50491296-7840b200-0a09-11e9-8392-204bf12b5edf.png)

**Comment by X3msnake** [comment]
Stock rabbit Model is zero thickness howllow with single normal wall that is why the slicer cannot slice it

![image](https://user-images.githubusercontent.com/11083514/50601590-8597e980-0eac-11e9-9ebc-f04e1d6a1b56.png)

![image](https://user-images.githubusercontent.com/11083514/50601686-d7407400-0eac-11e9-9c9b-a9a995964636.png)

**Comment by NardJ** [comment]
Ah good to hear it's not a bug :+1:
