### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rsilvers129** [Photonsters/Slicer#6]
Thank you for writing this.

I would love to use this slicer with a way to pick +- erode/dilate from 0-9 pixels in 2D.

https://www.youtube.com/watch?v=1jGO8q70zm8&fbclid=IwAR1ZEfVyjxla0oguIFQafXVwTqpO-Oq2wiv_80iNvKneqAgu8LAvaPSQiS4

**Comment by NardJ** [comment]
Nice video, maybe we should define this as a standard for future/videos. I was wondering if you need erode/dilate or that scale is more appropiate. Did you try scaling?

**Comment by rsilvers129** [comment]
Thank you. Yeah, tried that. Scaling won't work as the resin swell is not related to the part size. Tested the same resin on a Zortrax and got identical results to on my Photon. ChuTuBox saw my tests and agreed that they are adding resin profiles to their pro version for next year, but I think we need a free version now:

https://i.postimg.cc/RVH6nVgx/quad.jpg

**Comment by NardJ** [comment]
@rsilvers129 You say 

>  ChuTuBox saw my tests and agreed that they are adding resin profiles to their pro version for next year, but I think we need a free version now


Is this in issue #8?
